application/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView
from code_green.views import IndexView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('code_green:register_profile')


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('code_green/', include('code_green.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code_green/urls.py
from django.urls import path
from code_green.views import IndexView, RegisterProfileView, ProfileView, MissionsView, AboutView, LeaderboardView, \
    CommunityView

app_name = 'code_green'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
    path('missions/', MissionsView.as_view(), name='missions'),
    path('about/', AboutView.as_view(), name='about'),
    path('leaderboard/', LeaderboardView.as_view(), name='leaderboard'),
    path('community/', CommunityView.as_view(), name='community'),
]

code_green/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    controller = models.BooleanField(default=False)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Mission(models.Model):
    title = models.TextField(max_length=50)
    brief = models.TextField(max_length=200)
    points = models.IntegerField(default=5)

    def __str__(self):
        return self.title

code_green/forms.py
from django import forms
from django.contrib.auth.models import User
from code_green.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture', )

code_green/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from code_green.forms import UserProfileForm
from code_green.models import UserProfile, Mission


class IndexView(View):
    def get(self, request):
        return render(request, 'code_green/index.html')


class RegisterProfileView(View):
    form = UserProfileForm()
    context_dict = {}

    def get(self, request):
        self.context_dict['form'] = self.form
        return render(request, 'code_green/profile_registration.html', context=self.context_dict)

    def post(self, request):
        self.form = UserProfileForm(request.POST, request.FILES)

        if self.form.is_valid():
            profile = self.form.save(commit=False)
            profile.user = request.user
            profile.save()
        else:
            print(self.form.errors)

        return redirect(reverse('code_green:index'))


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})

        return user, user_profile, form

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('code_green:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'code_green/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('code_green:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('code_green:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'code_green/profile.html', context_dict)


class AboutView(View):
    def get(self, request):
        return render(request, 'code_green/about.html', {})


class MissionsView(View):
    @method_decorator(login_required)
    def get(self, request):
        missions = Mission.objects.all()
        return render(request, 'code_green/missions.html', {'missions_list': missions})


class CommunityView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'code_green/community.html', {})


class LeaderboardView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'code_green/leaderboard.html', {})

templates/code_green/about.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>About</h1>
    <p>Want to find out more about the foundations of our 'secret' environmental organisation? Continue reading...</p>
{% endblock %}

templates/code_green/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">
        <title>
            Code Green - {% block title_block %} Home {% endblock %}
        </title>
    </head>

    <body>
        <nav>
            <ul>
                <li><a href="{% url 'code_green:index' %}">Home</a></li>
                <li><a href="{% url 'code_green:about' %}">About</a></li>
                <!-- add authentication requirement to access this area... -->
                {% if user.is_authenticated %}
                    <li><a href="{% url 'code_green:missions' %}">Missions</a></li>
                    <li><a href="{% url 'code_green:leaderboard' %}">Leaderboard</a></li>
                    <li><a href="{% url 'code_green:community' %}">Community</a></li>
                    <li><a href="{% url 'code_green:profile' user.username %}">Profile</a></li>
                {% endif %}
            </ul>
        </nav>

        <main>
            {% block body_block %}{% endblock %}
        </main>
    </body>
</html>

templates/code_green/community.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Community
{% endblock %}

{% block body_block %}
    <h1>Community</h1>
    <p>Help to support your local community, link up with local agents and help to make the world a better place.</p>
{% endblock %}

templates/code_green/index.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
    <h1>Code Green</h1>
    <p>Your mission, should you choose to accept it is to improve the environment in your local area. We never run out
    of new and exciting missions to improve the environment. Sign up today to start your new job!</p>
{% endblock %}

templates/code_green/leaderboard.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Leaderboard
{% endblock %}

{% block body_block %}
    <h1>Leaderboard</h1>
    <p>Want to see how you stack up with other agents, view the leaderboard below!</p>

    <p>To be implemented...</p>
{% endblock %}

templates/code_green/missions.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Missions
{% endblock %}

{% block body_block %}
    <div>
        <h1>Missions</h1>
    </div>

    <div>
        {% if missions_list %}
            <div>
                {% for mission in missions_list %}
                    <p>Mission Title: {{ mission.title }}</p>
                    <p>Mission Brief: {{ mission.brief }}</p>
                    <p>Mission Points: {{ mission.points }}</p>
                    <br/>
                {% endfor %}
            </div>
        {% else %}
            <div>
                There are no available missions.
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/code_green/profile.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
    <div>
        <div>
            <h1>{{ selected_user.username }}'s Profile</h1>
        </div>
    </div>

    <div>
        <div>
            {% if user_profile.picture %}
                <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="300" height="300" alt="{{ selected_user.username }}'s profile image" />
                <br />
            {% else %}
                <img src="{% static 'images/people.jpg' %}" width="300" height="300" alt="blank profile picture"/>
            {% endif %}

            <p style="margin-left:30px;">Mission Points: {{ user_profile.points }}</p>

            <div style="margin-left:30px;">
                {% if selected_user == user %}
                    <form method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Update" />
                    </form>
                {% else %}
                    <p>
                        <strong>Website:</strong>
                        <a href="{{ user_profile.website }}">{{ user_profile.website }}</a>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/code_green/profile_registration.html
{% extends 'code_green/base.html' %}
{% load static %}

{% block title_block %}
    Register - Create Profile
{% endblock %}

{% block body_block %}
    <div>
        <div>
            <h1>Register Here - Create Your Profile</h1>
        </div>
    </div>

    <div>
        <div>
            <form method="post"
                  action="{% url 'code_green:register_profile' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Create Profile">
            </form>
        </div>
    </div>
{% endblock %}